# Generated by Django 5.1.7 on 2025-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
