# Generated by Django 5.1.7 on 2025-08-22 23:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_disponible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('fecha', 'cancha', 'hora_inicio', 'hora_fin')},
        ),
        migrations.AddField(
            model_name='cancha',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='creada_por_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('no_show', 'No se presentó'), ('completada', 'Completada')], default='confirmada', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 22, 23, 1, 55, 924512, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='HorarioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'hora_inicio'],
                'unique_together': {('hora_inicio', 'hora_fin')},
            },
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='disponible',
        ),
        migrations.CreateModel(
            name='ConfiguracionSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('activo', models.BooleanField(default=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cancha')),
                ('horarios_disponibles', models.ManyToManyField(blank=True, to='reservas.horariobase')),
            ],
            options={
                'ordering': ['cancha', 'dia_semana'],
                'unique_together': {('dia_semana', 'cancha')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cancha')),
                ('horarios_disponibles', models.ManyToManyField(blank=True, to='reservas.horariobase')),
            ],
            options={
                'unique_together': {('fecha', 'cancha')},
            },
        ),
    ]
