# Generated by Django 5.1.7 on 2025-08-22 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_options_alter_reserva_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracionsemana',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='configuracionsemana',
            name='cancha',
        ),
        migrations.RemoveField(
            model_name='configuracionsemana',
            name='horarios_disponibles',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ConfiguracionDia',
        ),
        migrations.DeleteModel(
            name='ConfiguracionSemana',
        ),
    ]
